[tool.poetry]
name = "hat-py-sdk"
version = "0.10.1"
description = ""
authors = ["rtatton <rdt17@proton.me>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rtatton/hat-py-sdk"
repository = "https://github.com/rtatton/hat-py-sdk"
keywords = ["dataswift", "hat", "python", "sdk"]
packages = [{ include = "hat", from = "src" }]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = { extras = ["dotenv"], version = "^1.9.1" }
keyring = "^23.7.0"
requests = "^2.28.1"
PyJWT = { extras = ["crypto"], version = "^2.4.0" }
humps = "^0.2.2"
CacheControl = "^0.12.11"
ulid-py = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
